//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claims
{
    using System;
    
    public enum CauseOfLossCode : int
    {
        Other = 0,
        Collision = 1,
        Explosion = 2,
        Fire = 3,
        Hail = 4,
        MechanicalBreakdown = 5
    }
}
